GET http://localhost:5000/articles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cGUiOiJKV1QifQ.eyJ1c2VybmFtZSI6Imp1c2xpbiIsImV4cCI6MTYxNzMzNzEzMX0.T4njeVsPxk765qCNx9ydZHkvWVJi0mhM3-l0QZuGxMtMCv0TMCjFnrTxxhFqnyLBFQJQD3ITFwIERkd3sdWgwA